# Generated by Django 4.1.6 on 2023-02-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('name', models.CharField(max_length=90)),
                ('marks', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
    ]
